export const pickRandom = (items) => items[Math.floor(Math.random() * items.length)]

export const weatherCopy = {
  'Clear Sky': [
    { title: 'Pure Blue Horizon', subtitle: 'Not a cloud in sight — perfect light from dawn to dusk.' },
    { title: 'Open Skies Ahead', subtitle: 'The sun rules today with unbroken brilliance.' },
    { title: 'Golden Daylight', subtitle: 'Crisp, clear air and bright horizons await.' },
    { title: 'Unbounded Sunshine', subtitle: 'Visibility is endless under a flawless canopy.' },
    { title: 'Azure Perfection', subtitle: 'A deep blue sky stretches from edge to edge.' },
    { title: 'Radiant Clarity', subtitle: 'Sharp shadows and vivid colours define the day.' },
    { title: 'Full Sun Exposure', subtitle: 'Maximum UV index — shade and sunscreen recommended.' },
    { title: 'Pristine Atmosphere', subtitle: 'The cleanest air you will breathe all week.' },
    { title: 'Daybreak Brilliance', subtitle: 'Sunrise paints the sky in rich, unfiltered gold.' },
    { title: 'Celestial Calm', subtitle: 'Stillness overhead; a day made for the outdoors.' },
  ],
  'Mainly Clear': [
    { title: 'Mostly Bright', subtitle: 'A few whispers of cloud, but sunshine leads the way.' },
    { title: 'Light Veil Overhead', subtitle: 'Thin high cloud softens the light without hiding it.' },
    { title: 'Sun with Accents', subtitle: 'Scattered wisps add drama to an otherwise clear sky.' },
    { title: 'Near-Perfect Day', subtitle: 'Almost entirely clear — enjoy it while it lasts.' },
    { title: 'Soft Morning Glow', subtitle: 'Haze fades as the sun climbs higher.' },
    { title: 'Hazy Sunshine', subtitle: 'Warm and bright with a gentle milky tint.' },
    { title: 'Broadly Fine', subtitle: 'Cloud cover stays well under ten percent.' },
    { title: 'Open Gaps of Blue', subtitle: 'Thin patches let the sky shine through.' },
    { title: 'Agreeable Warmth', subtitle: 'Comfortable temperatures under a largely open sky.' },
    { title: 'Late-Day Clarity', subtitle: 'Any morning haze burns off by noon.' },
  ],
  'Partly Cloudy': [
    { title: 'Soft Cloud Layers', subtitle: 'A gentle, diffused atmosphere with shifting shade.' },
    { title: 'Sun and Shadow Play', subtitle: 'Light breaks through the clouds in moving patches.' },
    { title: 'Mixed Conditions', subtitle: 'Bright spells trade places with cloudy intervals.' },
    { title: 'Dappled Skies', subtitle: 'Light and shade dance across the landscape.' },
    { title: 'Intermittent Sunshine', subtitle: 'Clouds come and go, but warmth persists.' },
    { title: 'Silver-Lined Clouds', subtitle: 'Every break in the clouds rewards with golden light.' },
    { title: 'Varied Canvas', subtitle: 'A painter\'s sky — blue, white, and grey in motion.' },
    { title: 'Breezy Outlook', subtitle: 'Clouds are moving fast, keeping conditions lively.' },
    { title: 'Dynamic Atmosphere', subtitle: 'The sky tells a new story every hour.' },
    { title: 'Threshold of Change', subtitle: 'Could go either way — watch the horizon.' },
  ],
  'Overcast': [
    { title: 'Grey Blanket Above', subtitle: 'A flat, uniform cloud deck mutes the light.' },
    { title: 'Muted Daylight', subtitle: 'Diffuse light softens every edge and shadow.' },
    { title: 'Leaden Sky', subtitle: 'Heavy cloud presses down with quiet persistence.' },
    { title: 'Wool Clouds Everywhere', subtitle: 'The sky is one seamless grey from rim to rim.' },
    { title: 'Subdued Atmosphere', subtitle: 'Calm and cool under an unbroken overcast.' },
    { title: 'Flat Light Conditions', subtitle: 'Photographers note: perfect for portraits today.' },
    { title: 'Cloud Ceiling Low', subtitle: 'The cloud base sits close, giving the world a cosy feel.' },
    { title: 'Dim but Dry', subtitle: 'Overcast skies without the rain — for now.' },
    { title: 'Pewter Horizon', subtitle: 'A monochromatic palette dominates the day.' },
    { title: 'Indoor Kind of Day', subtitle: 'Grab a coffee — the sky has closed for business.' },
  ],
  'Foggy': [
    { title: 'Shrouded in Mist', subtitle: 'Visibility drops as fog wraps the landscape in white.' },
    { title: 'Ghostly Morning', subtitle: 'Familiar shapes dissolve into soft grey walls.' },
    { title: 'Pea-Soup Conditions', subtitle: 'Dense fog reduces visibility to metres.' },
    { title: 'Ethereal Haze', subtitle: 'The world softens at its edges in the mist.' },
    { title: 'Dreamlike Fog', subtitle: 'Silhouettes emerge and vanish in the murk.' },
    { title: 'Moisture-Laden Air', subtitle: 'Fog droplets settle on every surface.' },
    { title: 'Zero Visibility Warning', subtitle: 'Drive slowly and keep your lights on.' },
    { title: 'Suspended Silence', subtitle: 'Sound is absorbed and distances are deceiving.' },
    { title: 'Milky White Skies', subtitle: 'The sun hides behind a veil it cannot pierce.' },
    { title: 'Fog-Wrapped World', subtitle: 'A quiet, intimate atmosphere hangs over everything.' },
  ],
  'Light Drizzle': [
    { title: 'Fine Rain Curtain', subtitle: 'Barely-there droplets dampen without soaking.' },
    { title: 'Misting Hour', subtitle: 'The air is wet before the sky opens up.' },
    { title: 'Gentle Patter', subtitle: 'Soft drizzle taps on windows and leaves.' },
    { title: 'Grey and Damp', subtitle: 'Not quite rain, but an umbrella wouldn\'t hurt.' },
    { title: 'Light Spray Day', subtitle: 'A fine mist coats everything in a thin film.' },
    { title: 'Soft Drizzle', subtitle: 'Breezy and damp with occasional fine rain.' },
    { title: 'Misty Conditions', subtitle: 'Visibility stays good but hair will curl.' },
    { title: 'Dewy Afternoon', subtitle: 'Droplets cling to surfaces without forming puddles.' },
    { title: 'Cloud Spitting', subtitle: 'The clouds are trying, but barely committing.' },
    { title: 'Barely Raining', subtitle: 'Light enough to ignore, heavy enough to notice.' },
  ],
  'Dense Drizzle': [
    { title: 'Heavy Mist Falling', subtitle: 'Drizzle thick enough to obscure distant views.' },
    { title: 'Saturated Air', subtitle: 'Every breath carries moisture; everything stays wet.' },
    { title: 'Drizzle Downpour', subtitle: 'Dense drops fall steadily without becoming full rain.' },
    { title: 'Soaking Mist', subtitle: 'Slow but relentless — a full raincoat is essential.' },
    { title: 'Persistent Dampness', subtitle: 'The drizzle refuses to stop all day long.' },
    { title: 'Fog-Rain Hybrid', subtitle: 'Somewhere between fog and rain — miserable either way.' },
    { title: 'Continuous Fine Rain', subtitle: 'Umbrellas up; this won\'t clear for hours.' },
    { title: 'Wet and Dreary', subtitle: 'Dense drizzle flattens the light and mood.' },
    { title: 'Damp Ceiling', subtitle: 'Cloud base near the ground; drizzle fills the gaps.' },
    { title: 'Invisible Rain', subtitle: 'You don\'t see it coming until you\'re already soaked.' },
  ],
  'Rain': [
    { title: 'Rain Is Here', subtitle: 'Steady drops are falling — grab an umbrella.' },
    { title: 'Wet Pavement Day', subtitle: 'Puddles form as rain taps a steady rhythm.' },
    { title: 'Showers Setting In', subtitle: 'Rain arrives and settles in for the day.' },
    { title: 'Overcast and Wet', subtitle: 'Grey skies deliver a reliable, persistent rain.' },
    { title: 'April Downpour', subtitle: 'Classic seasonal rain that fills the reservoirs.' },
    { title: 'Steady Rainfall', subtitle: 'Consistent intensity with no sign of letting up.' },
    { title: 'Rain-Washed Streets', subtitle: 'The city glistens as water flows through every gutter.' },
    { title: 'Moderate Precipitation', subtitle: 'Enough to drench you in minutes — stay covered.' },
    { title: 'Cloud Emptying', subtitle: 'The sky has been holding this for days.' },
    { title: 'Grey and Dripping', subtitle: 'Everything outside is thoroughly wet by midday.' },
  ],
  'Heavy Rain': [
    { title: 'Torrential Downpour', subtitle: 'Rain hammers down in curtains — stay inside if you can.' },
    { title: 'Flooding Possible', subtitle: 'Heavy rain threatens low-lying areas; check local alerts.' },
    { title: 'Relentless Deluge', subtitle: 'The rain is intense, sustained, and unforgiving.' },
    { title: 'Bucketing Down', subtitle: 'Heavy drops pound the ground without mercy.' },
    { title: 'Severe Rainfall', subtitle: 'Conditions deteriorate rapidly as rain intensifies.' },
    { title: 'Roads Running Like Rivers', subtitle: 'Surface water is a real hazard today.' },
    { title: 'Wall of Water', subtitle: 'The rain arrives in sheets, reducing visibility sharply.' },
    { title: 'Storm-Level Rain', subtitle: 'Heavy enough to be worth a weather warning.' },
    { title: 'Non-Stop Soaking', subtitle: 'Hours of heavy rain expected with no breaks.' },
    { title: 'Sky Has Opened Up', subtitle: 'Rain so heavy it drowns out conversation.' },
  ],
  'Snow': [
    { title: 'Winter Texture', subtitle: 'Snow settles slowly, coating the world in white.' },
    { title: 'Crisp Cold Beauty', subtitle: 'Flakes fall in the hush of a snowy afternoon.' },
    { title: 'Snowflake Season', subtitle: 'Gentle snowfall dusts rooftops and branches.' },
    { title: 'Fresh Powder Day', subtitle: 'Light snow accumulates into a soft white blanket.' },
    { title: 'Silent White Descent', subtitle: 'Snow muffles sound and softens every surface.' },
    { title: 'Frost and Flurries', subtitle: 'Cold air carries flakes in swirling eddies.' },
    { title: 'Snowy Landscape Ahead', subtitle: 'The ground is already turning white.' },
    { title: 'Ice-Flecked Air', subtitle: 'Fine snow crystals glitter in the pale light.' },
    { title: 'Wintry Blanket', subtitle: 'Snow covers everything in a clean layer of white.' },
    { title: 'Seasonal Snowfall', subtitle: 'Classic winter snow at a manageable pace.' },
  ],
  'Heavy Snow': [
    { title: 'Blizzard Conditions', subtitle: 'Heavy snow and wind bring near-whiteout visibility.' },
    { title: 'Deep Drifts Forming', subtitle: 'Snow piles up fast; roads are becoming impassable.' },
    { title: 'Arctic Assault', subtitle: 'Intense snowfall buries the landscape rapidly.' },
    { title: 'Snow Emergency', subtitle: 'Heavy snowfall may disrupt travel and services.' },
    { title: 'White-Out Warning', subtitle: 'Visibility falls dangerously in the heavy snow.' },
    { title: 'Accumulation Alert', subtitle: 'Several centimetres per hour are falling now.' },
    { title: 'Rooftops Straining', subtitle: 'Weight of snow is significant — clear with care.' },
    { title: 'Footprint Deep', subtitle: 'You\'ll sink ankle-deep with every step outside.' },
    { title: 'Relentless Winter Storm', subtitle: 'Snow will keep falling well into the night.' },
    { title: 'Total Whiteout', subtitle: 'The world disappears behind a wall of white.' },
  ],
  'Snow Grains': [
    { title: 'Icy Granules Falling', subtitle: 'Tiny ice pellets sting and crunch underfoot.' },
    { title: 'Graupel Shower', subtitle: 'Small, round ice crystals tap down like buckshot.' },
    { title: 'Sleet-Like Grains', subtitle: 'Between snow and ice — not pleasant either way.' },
    { title: 'Frozen Specks', subtitle: 'Grains of ice patter against every hard surface.' },
    { title: 'Winter Grit', subtitle: 'Fine ice particles settle without mercy.' },
    { title: 'Pellet Precipitation', subtitle: 'Hard snow grains bounce off the pavement.' },
    { title: 'Frozen Drizzle', subtitle: 'Water droplets freeze before they land.' },
    { title: 'Icy Mist', subtitle: 'The air sparkles with tiny frozen particles.' },
    { title: 'Crunchy Underfoot', subtitle: 'A thin glassy layer crunches with every step.' },
    { title: 'Wintry Mix', subtitle: 'Ice grains mix with cold air in an unpleasant blend.' },
  ],
  'Rain Showers': [
    { title: 'Passing Showers', subtitle: 'Bursts of rain come and go throughout the day.' },
    { title: 'Shower Spells', subtitle: 'Heavy downpours fade quickly — carry an umbrella.' },
    { title: 'April Showers', subtitle: 'Brief, frequent showers punctuate an otherwise damp day.' },
    { title: 'On and Off Rain', subtitle: 'Rain arrives in waves rather than continuous falls.' },
    { title: 'Scattered Downpours', subtitle: 'Some spots get drenched while others stay dry.' },
    { title: 'Quick-Moving Showers', subtitle: 'Showers arrive fast and leave just as quickly.' },
    { title: 'Squally Intervals', subtitle: 'Gusts and showers combine for blustery conditions.' },
    { title: 'Patchy Precipitation', subtitle: 'Rain is concentrated in localised shower clouds.' },
    { title: 'Shower Activity High', subtitle: 'Multiple cells bring repeated bursts of rain.' },
    { title: 'Hit and Run Rain', subtitle: 'You barely dry out before the next shower arrives.' },
  ],
  'Violent Rain Showers': [
    { title: 'Extreme Downpour', subtitle: 'Violent showers dump rain faster than it can drain.' },
    { title: 'Tropical-Intensity Rain', subtitle: 'Short but brutal — flash flooding is a real risk.' },
    { title: 'Sudden Deluge', subtitle: 'Rain intensity spikes to dangerous levels without warning.' },
    { title: 'Severe Shower Alert', subtitle: 'These showers are powerful enough for a weather warning.' },
    { title: 'Flash Flood Risk', subtitle: 'Violent bursts of rain overwhelm drainage systems.' },
    { title: 'Wall of Rain', subtitle: 'The shower arrives like a curtain of water.' },
    { title: 'Explosive Precipitation', subtitle: 'Convective cells release energy as driving rain.' },
    { title: 'Seek Shelter Now', subtitle: 'Violent rain reduces visibility to near zero instantly.' },
    { title: 'Extreme Weather Event', subtitle: 'Conditions are hazardous; stay away from flood-prone areas.' },
    { title: 'Rain at Full Force', subtitle: 'Nothing holds up in this level of rainfall.' },
  ],
  'Snow Showers': [
    { title: 'Wintry Squalls', subtitle: 'Snow bursts sweep through, leaving fresh white patches.' },
    { title: 'Flurry Activity', subtitle: 'Intermittent snow showers keep conditions wintry.' },
    { title: 'Snow on and Off', subtitle: 'Brief but intense snow showers throughout the day.' },
    { title: 'Cold Shower Spells', subtitle: 'Showers bring snow at low temperatures.' },
    { title: 'Blowing Snow Periods', subtitle: 'Wind drives snow horizontally in squall bursts.' },
    { title: 'Wintry Intervals', subtitle: 'Snow showers between brief brighter spells.' },
    { title: 'Unsettled and Snowy', subtitle: 'Conditions fluctuate with frequent snow showers.' },
    { title: 'Icy Squalls', subtitle: 'Each shower brings a fresh sting of cold.' },
    { title: 'White-Out Moments', subtitle: 'Visibility drops sharply during each shower.' },
    { title: 'Blustery Snow', subtitle: 'Wind and snow conspire to make it feel far colder.' },
  ],
  'Thunderstorm': [
    { title: 'Electric Skies', subtitle: 'Lightning splits the sky as thunder rolls across the valley.' },
    { title: 'Storm Front Moving In', subtitle: 'Dark clouds build as a powerful storm approaches.' },
    { title: 'Thunder and Lightning', subtitle: 'Nature\'s light show arrives with force and noise.' },
    { title: 'Charged Atmosphere', subtitle: 'The air crackles before the first lightning bolt strikes.' },
    { title: 'Severe Thunderstorm', subtitle: 'Heavy rain, frequent lightning, and strong gusts expected.' },
    { title: 'Sky Unleashed', subtitle: 'Towering cumulonimbus releases its full energy.' },
    { title: 'Bolt from the Blue', subtitle: 'Lightning can strike far ahead of the main storm cell.' },
    { title: 'Dramatic Weather Event', subtitle: 'Stay indoors; this storm means business.' },
    { title: 'Rumbling Overhead', subtitle: 'Thunder echoes continuously as the storm passes.' },
    { title: 'Nature\'s Power Display', subtitle: 'A thunderstorm reminds us who is really in charge.' },
  ],
  'Thunderstorm with Hail': [
    { title: 'Hail and Thunder Combine', subtitle: 'Ice pellets and lightning make a dangerous partnership.' },
    { title: 'Extreme Storm Warning', subtitle: 'Large hailstones and severe lightning expected.' },
    { title: 'Hailstone Bombardment', subtitle: 'Cover your car — hail can cause serious damage.' },
    { title: 'Ice and Fire in the Sky', subtitle: 'Frozen hail and electrical storms strike simultaneously.' },
    { title: 'Violent Convective Storm', subtitle: 'Severe updrafts produce hail and intense lightning.' },
    { title: 'Seek Shelter Immediately', subtitle: 'Hail and lightning together are life-threatening outside.' },
    { title: 'Storm Cell Overhead', subtitle: 'The most intense part of the storm passes directly over.' },
    { title: 'Pounding Hail Shower', subtitle: 'Ice pellets drum on every surface like gravel.' },
    { title: 'Supercell Signature', subtitle: 'Classic hail-producing storm structure is visible on radar.' },
    { title: 'Catastrophic Conditions', subtitle: 'Property damage and hazardous travel are both likely.' },
  ],
  'Unknown': [
    { title: 'Mysterious Skies', subtitle: 'Something is happening up there — hard to say what.' },
    { title: 'Today\'s Conditions', subtitle: 'Live data coming straight from your Weather API.' },
    { title: 'Weather in Progress', subtitle: 'The atmosphere is doing something interesting.' },
    { title: 'Nature\'s Surprise', subtitle: 'Expect the unexpected when skies behave unusually.' },
    { title: 'Check Back Soon', subtitle: 'Conditions are changing faster than we can track.' },
    { title: 'Undefined Weather', subtitle: 'A rare code no one planned for — stay alert.' },
    { title: 'Unsettled Outlook', subtitle: 'The sky hasn\'t made up its mind today.' },
    { title: 'Atmospheric Anomaly', subtitle: 'Unusual readings suggest something out of the ordinary.' },
    { title: 'Variable Conditions', subtitle: 'Difficult to categorise — plan for anything.' },
    { title: 'Wild Card Day', subtitle: 'When in doubt, pack layers and an umbrella.' },
  ],
}

export const defaultCopy = weatherCopy['Unknown']
